### PR TITLE
No filter class

### PR DESCRIPTION
**Pull request by hover2pi**
Removed `core.Filter()` class and put it into a separate module named `svo_filters` located [here](https://github.com/hover2pi/svo_filters).

### CODE REVIEW

**Comment by hover2pi** [comment]
I completely pulled the `Filter` class out of the package and made `svo_filters` a dependency. I also fixed the `ModelGrid` interpolation in `core.py` so that the pre-loaded flux grid is reloaded after `ModelGrid.customize()` is run.

**Comment by mattjhill** [comment]
Are you planning on adding `svo_filters` to PyPI?  I don't think we should introduce dependencies unless they can be installed with a package manager.

**Comment by hover2pi** [comment]
Just added it to PyPI. `pip install svo_filters`

**Comment by mattjhill** [comment]
Just make sure it gets added to all of the dependency lists.

`.rtd-environment.yaml`
`.travis.yaml`
`setup.cfg`

**Comment by exowanderer** [comment]
Everytime I read "no filter" I think about the Instagram "no filter" bs an the meme's associated with it

**Comment by mattjhill** [comment]
The pr test is showing fail because I canceled the Mac builds, but everything else passed so I'm merging.

**Pull request merged**
