### PR TITLE
[WIP]: Small Web app improvements

### LINKED ISSUE #407: Mu cutoff on the online limb-darkening calculator should be on the "model" and not the "star"
Hi folks,

 On today's ExoCTK team meeting, @JeffValenti suggested that the mu cutoff value that is asked to the user on the online tool shouldn't be a stellar property, but rather part of the model (i.e., be on the same spot where the limb-darkening law is defined). A picture is worth more than my previous 308 characters:

Screen Shot 2020-09-01 at 5 18 06 PM

 I'm assigning @hover2pi to this for efficiency, and also assigning low priority to this (set to v1.2 of ExoCTK).

N.

### PR DESCRIPTION
**Pull request by hover2pi**
Moved mu_min div in LDC form and downgraded werkzeug to work with scipy v1.5.2.

Fixes #407

### CODE REVIEW

**Comment by hover2pi** [comment]
Also adding #395 to this PR.

**Review by nespinoza — APPROVED** [review]
Hey @hover2pi --- just checked this on a local version and all looks good! Approving this to be merged.

N.

**Comment by hover2pi** [comment]
@nespinoza Shall I deploy?

**Comment by hover2pi** [comment]
I deployed it to the test server and everything is fine but the production server needs a Python update (#411 ) before I can pull from master to include these updates.

**Comment by nespinoza** [comment]
OK! Also, I would really like to deploy everything at once instead of deploying on a tool-to-tool basis, so as to be consistent with the ExoCTK v.1.1 project (https://github.com/orgs/ExoCTK/projects/11).

**Comment by nespinoza** [comment]
FYI: the limb-darkening version in the test server still has the issues outlined in https://github.com/ExoCTK/exoctk/issues/372 --- not in the web-version, but on the downloaded coefficients (once you click "Download Coefficient Tables"). It appears this was fixed by https://github.com/ExoCTK/exoctk/pull/381 in the web app, but _not_ on the coefficients that are printed for download.

Should I open another ticket for that?

**Pull request merged**
