### PR TITLE
contamination : allow local option for Miri and nircam

### PR DESCRIPTION
**Pull request by jaymedina**
This PR includes:
- Updated text on the website that links people to our JDocs contam article where they can see how to generate contamination plots for NIRSS, NIRCam, MIRI locally. 
- Re-naming the sossFieldSim and sossContamFig modules to a general name. 
- A new user-friendly script that will allow users to generate contamination plots locally for NIRISS, NIRCam, and MIRI, using 1 command

And accompanies the updated JDocs article for contam: https://jwst-docs.stsci.edu/display/JDOX/.Contamination+Overlap+Tool+v1.1#id-.ContaminationOverlapToolv1.1-PCCContaminationCalculatorforNIRCamandMIRImodes(AvailableLocally)

<b>Checks to run</b>:

- [ ] On `tlexo` generate WASP 17b contam with NIRISS
- [x] Check for typos 
- [x] Check that links work
- [x] Run contam tool on a local web session (in python 3.6 env) to make sure NIRISS SOSS is working normally

Locally generate WASP 17b contam with:
- [x] NIRISS (compare with results from website to make sure it's the same)
- [x] NIRCam (check with `contamVerify`)
- [x] MIRI (check with `contamVerify`)

- [x] test binComp parameter in `make_contam_plot.py`

### CODE REVIEW

**Comment by jaymedina** [comment]
Just some results from my tests: 



<b>NIRISS SOSS contam for WASP 17-b </b>
On website:
image

Locally: 
image

**Comment by jaymedina** [comment]
OK @bourque I think the latest commit should fix the issue you were having. 

What happened was there is no source in the 2MASS point-source catalog with those coordinates that were put in, so the algorithm just pulled the next closest source as the "target", which is incorrect. I've made it so the code will catch this and raise an Exception error if no target is found, instead of going thru everything with the wrong target.

**Comment by jaymedina** [comment]
OK @nespinoza so Matthew finished running his tests and I finished running my last one on MIRI. Feel free to test run the `make_contam_plots.py` script on a few of your own targets just to be safe, but I think this is good to go.

**Comment by jaymedina** [comment]
OK, added the figure explication that will be generated with every bokeh image to be consistent with the website. That wraps up this PR and you can merge after review @nespinoza 

image

**Review by nespinoza — APPROVED** [review]
All right, tested on my end and all works!

**Pull request merged**
