### PR TITLE
v1.1.1

### PR DESCRIPTION
**Pull request by hover2pi**
Fixes LDC issues in v1.1.0.

### CODE REVIEW

**Comment by hover2pi** [comment]
Ok, this is ready to ride, @bourque !

**Comment by bourque** [comment]
@hover2pi The code changes here look good to me!

For consistency's sake, could this branch name be changed from `r1.1.1` to simply `1.1.1`?  Not a huge deal, but if it is easy to do, it would be nice:

Screen Shot 2021-04-08 at 09 02 12

Additionally, a similar PR should be opened that merges `1.1.1` into `master`:

git_workflow

**Comment by bourque** [comment]
@hover2pi I would be ideal if this could be sorted out before we do the `v1.2` release next Monday.  I would be happy to change the branch name (see previous comment) and merge this if you would like, just let me know!  Thanks.

**Comment by hover2pi** [comment]
Yes! This should be merged. This is the v1.1.1 release. Thanks @bourque !

**Review by bourque — APPROVED** [review]

**Comment by bourque** [comment]
This PR is being replaced by #493 so that the branch name is consistent with the ExoCTK releases (i.e. `1.1.1` instead of `r1.1.1`)

**Pull request closed without merging**
