### PR TITLE
Update exoctk data download link on homepage

### PR DESCRIPTION
**Pull request by bourque**
This PR updates the "ExoCTK Data Download" link of the ExoCTK webpage, which has been triggering an automatic download, but failing (#296).  The link now redirects to the "Obtain ExoCTK data" section of the README file.

This PR also updates said section of the README file, which now gives two options: either run the `exoctk.utils.download_exoctk_data()` function, or download directly from the public Box folder (which is linked).

### CODE REVIEW

**Comment by bourque** [comment]
@nespinoza Could you review?

**Comment by bourque** [comment]
Closes #368

**Comment by nespinoza** [comment]
Hey @bourque! Sure thing. Quick question: Travis CI is failing for some python 3 versions --- is that normal? All the errors seem to be due to a pytest incompatibiity and not with the code itself.

**Comment by bourque** [comment]
@nespinoza Yeah, i've been trying to figure that one out.  Most of our recent PRs have been failing on Python 3.5.   It is one reason I opened #366, hoping that I can solve this by simply removing the environment.  But if we want to continue to support 3.5, I can dig into it.

**Comment by nespinoza** [comment]
Hi @bourque!

 I've reviewed the changes and they look good to me! Let's go ahead and merge this.

N.

**Pull request merged**
