### PR TITLE
Adding Chimera Functionality to ExoCTK

### PR DESCRIPTION
**Pull request by mfixstsci**

### CODE REVIEW

**Comment by mfixstsci** [comment]
Feel free to try it out, this is what I've got so far!
```
import os
from exoctk.atmospheric_retrievals.chimera import PlanetarySystem

ps = PlanetarySystem()

# Download and unzip first: https://www.dropbox.com/sh/o4p3f8ukpfl0wg6/AADBeGuOfFLo38MGWZ8oFDX2a?dl=0&lst=
ps.directory = os.path.join(<path_to_h5_files>, 'ABSCOEFF_CK')
ps.stellar_parameters = {'stellar_file': 'sum_star.h5',
                         'temp': 5000,
                         'logmh': 0 ,
                         'logg': 4.0,
                         'stellar_db': 'phoenix'}

ps.observatory = "HST"
ps.wavenumber_min, ps.wavenumber_max = 2000, 3000

ps.make_stellar_model()
ps.calculate_cross_sections()
vars(ps)
```

**Comment by nespinoza** [comment]
Hi @mfixstsci,

 This is fantastic, thanks a ton! Just tested it and works like a charm!
 
 After playing with this, I think I'm not convinced the cross-sections should be a function of the `PlanterySystems`. I think the best would be for those to be objects of their own (so create another class, `CrossSections` or something of the like), so then we can do something like:
 
     from exoctk.atmospheric_retrievals.chimera import CrossSections
     
     # Load cross-sections:
     cross_sections = CrossSections()
     cross_sections.directory = os.path.join(<path_to_h5_files>, 'ABSCOEFF_CK')
     cross_sections.calculate()

     # Generate transit spectrum:
     ps.get_transmission_spectrum(cross_sections)

The philosophical reason behind `CrossSections` having its own class is that, really, the cross-sections involve knowledge from experiments/calculations here on Earth by different groups around the world; so they are, in essence, not "properties" of the planetary system itself (like the other parts of the physical model we are defining for the planetary/star system, for instance), but rather form part of the hypothesis involved on the model. Every set of cross-section around the world has typically a different set of assumptions behind.

 Does that make sense? I think it shouldn't be too complex to make the change, right?

 Thanks!
Néstor

**Comment by mfixstsci** [comment]
@nespinoza I went ahead and structured the cross sections part of the algorithm. My logic was as follows:

- Have the `PlanetarySystem` object only contain attributes that represent the Star Planet system.
- `LoadCrossSections` can load the cross sections based what the user defines in `PlanetarySystem`. I made a json version of the system to make the process a little easier. `LoadCrossSections` inherits the `PlanetarySystem` attributes and methods.
```
from exoctk.atmospheric_retrievals.chimera import LoadCrossSections
xsects = LoadCrossSections(data_directory='<path_to_h5_files>', planetary_system_file='exoctk/atmospheric_retrievals/wfc3_free_retrieval_transmission.json')
```
- A new class called `GenerateModel` that will perform all of the modeling bits and make some plots. This is still a work in progress atm but I am almost ready to plot the results.

**Comment by mfixstsci** [comment]
Since we decided to deprecate atmospheric retrievals from our project, I will close this PR now 🪦

**Pull request closed without merging**
