### PR TITLE
Changing the naming convention.

### PR DESCRIPTION
**Pull request by julesfowler**
There's a lot going on here -- so I would appreciate a quick eye.

While I was neatening things up -- I went ahead and took out the SURPRISING number of entirely empty modules?

These changes are up on `tlexo` and I did some quick testing, but I'd appreciate if you feel like double checking me.

### CODE REVIEW

**Comment by julesfowler** [comment]
@hover2pi Okay -- now it's ACTUALLY up and running on `tlexo` -- jeeze louise where there a lot of nested `setup.py` files for that `C` monster...

**Comment by hover2pi** [comment]
Hmmm... tlexo is down!

**Comment by julesfowler** [comment]
It's back now!

**Comment by julesfowler** [comment]
@hover2pi This has to go arm in arm with the website change.

**Pull request merged**
