### PR TITLE
[WIP]: Phase constraint tool

### PR DESCRIPTION
**Pull request by catherine-martlin**
Currently struggling with reading in the default of the arg parse values. Could hard code it, but that seems less neat.

### CODE REVIEW

**Comment by catherine-martlin** [comment]
This is not ready to be merged yet, but I wanted to create the work in progress PR so that others know it's being worked on.

**Comment by mfixstsci** [comment]
Hey @catherine-martlin! I am going to be in contact with someone in the archives branch sometime this week to get some information about how to use the ExoMAST python API to fetch the meta data and populate it in the webpage. I was going to work from this PR and write the `def get_transit_details` function, you okay with me working off your PR?

**Comment by catherine-martlin** [comment]
Yep! That’s perfect and why I set it up and pushed the branch - despite still working on the main function/dealing with the argparse stuff. The main function runs, but the if/else set up needs more work and is clunky. But I wanted you to have the general structure so you could get started too.

I’m planning to bring up some of my questions/ask for advice on the script layout at the meeting today and we can chat then about your function/ideas for that too hopefully.
________________________________

**Comment by catherine-martlin** [comment]
Fantastic @mfixstsci! I'll get your updates and then do a pass through to update the main function/methods of parameter input later this week. I want to first check the current codes in use by other functions for similar types of input types that we'll use on our web app. If I do think there's a need or use for the docopt option then I'll definitely reach out to you about that!

**Comment by mfixstsci** [comment]
@catherine-martlin, I am playing around with the tool and was thinking about doing some overhauling to the parser. I think that we should require the users to input data instead of providing defaults for a few of the parameters (target_name, period, t0, etc). What are your thoughts?

**Comment by catherine-martlin** [comment]
@mfixstsci  - I agree that for our uses providing defaults isn't what we need - I just removed the entirety of argparse as it doesn't work well for us. I set all the parameters to `None`, if someone provides an actual value then my plan is for the code to use that, otherwise if the value stays `None` then our code should find it and set that value. 

Things I think to be done: 
- [ ] Error message if a Target name isn't provided by the user. 
- [ ] What form should our final output to the user be in? Will that be using t0 as we currently don't use that I think. (Should it be an addition of minphase/maxphase to the time of t0?)
- [ ] Once we have input/output set we should think of what tests/errors we want to build in to provide users with guidance and support.

**Comment by mfixstsci** [comment]
I added `docopt` as a way to parse arguments. We should discuss this with the team before moving forward or adding it as a dependency! I am still trying to figure out if you can declare a default datatype for the arguments because right now everything is passed in as strings :(

**Pull request merged**
