### PR TITLE
Closing some small easily fixable issues

### PR DESCRIPTION
**Pull request by hover2pi**
- [x] Remove LDC uniform profile (#486 )
- [x] Remove `lmfit` support (#415 )
- [x] Fix mislabeled Phoenix model (#251 )
- [x] Fix logging issue on `plexo` (#485 )

### CODE REVIEW

**Comment by hover2pi** [comment]
The mislabeled Phoenix model is corrected now. And Trappist-1 gets matched with the correct model as well.

**Comment by hover2pi** [comment]
RTD build is failing for `batman-package==2.4.6`.

**Comment by hover2pi** [comment]
This is verrrry frustrating. I changed nothing and now all the tests are failing when trying to install `pysynphot`.

**Comment by bourque** [comment]
@hover2pi I just encountered the same issue in #517.  Maybe that team updated something in their `pypi` release?  Seems like its something that happened on their end, not ours.

**Comment by bourque** [comment]
@hover2pi It looks like the `2to3` issue fixed itself!  Everything appears to be passing now.

**Comment by bourque** [comment]
Alright, im gonna merge this so we can get it into #525

**Comment by bourque** [comment]
This PR was going to merge into `master` instead of `develop`.  I switched the base and now there are a few conflicts.  I will solve these before merging.

**Pull request merged**
