### PR TITLE
Updated groups_integrations tool with new name

### PR DESCRIPTION
**Pull request by hover2pi**
Addresses issue #149 by updating the tool name in the embedded web app.

### CODE REVIEW

**Comment by hover2pi** [comment]
Ahhhh!! Thar be dragons!

I just realized we need to PEP8/257 the web app AND update the `log_exoctk.py` calls with only the currently implemented tools. Ugh.

**Comment by hover2pi** [comment]
Ok @julesfowler this is ready to go!

**Comment by hover2pi** [comment]
@julesfowler A gentle ping on this! Sorry if you're swamped. I didn't want to reassign the review since this subpackage is one of yours!

**Comment by julesfowler** [comment]
I like `grints` as a wombo -- work combo.

**Comment by hover2pi** [comment]
That wombo was no accident @julesfowler . I reset the README as requested!

**Comment by hover2pi** [comment]
@julesfowler OK! Now it's passing. I made a new release of svo_filters with boat loads of tests and it seems to work. Merge away!

**Pull request merged**
