### PR TITLE
Catalog parsing

### PR DESCRIPTION
**Pull request by mfixstsci**
Adding catalog parsing for targets with multiple catalog entries for the ExoMAST retrieval and form population.

### CODE REVIEW

**Comment by hover2pi** [comment]
@mfixstsci Is this WIP or ready for review?

**Comment by mfixstsci** [comment]
@hover2pi this ready for review! Sorry for the confusion

**Comment by mfixstsci** [comment]
I also added a dynamic link to the UI. If we need to remove that from this PR thats fine. Will probably make the merging process easier.

**Comment by kevin218** [comment]
Line 25: The following line should be added back in: `from sqlalchemy import create_engine`

**Comment by mfixstsci** [comment]
I went ahead and cleaned up the conflicts. It didn't like that I didn't have the changes for the form validation work that @hover2pi has been implementing. Should be ready for review

**Comment by hover2pi** [comment]
I added this to #245 so I'll close this. Thanks @mfixstsci !

**Pull request closed without merging**
