### PR TITLE
Hot fix for groups and integrations.

### PR DESCRIPTION
**Pull request by julesfowler**
This is a not particularly elegant fix for #282.

It looks like for some reason when you open the Groups and Integrations Calculator, it's trying to form submit right then and there. (I would bet this is true for all/most of the other API wrapped forms) but this one needs to immediately do math operations on the at this time empty inputs, and the attempted type casting of nothing throws an error.

My fix for now is to catch this error, make sure it's a nonetype, and give it a chance to chill and see if some more input gets thrown that way. For the case that (I'm not sure exists but 🤷‍♂ ) I wrote a little custom message and rerouted it to the error template. 

@mfixstsci I would definitely like your input in case this has unforseen complications.

### CODE REVIEW

**Comment by julesfowler** [comment]
@mfixstsci or @bourque Actually hold off on reviewing this for now. I have discovered some angry problems to fix.

**Comment by julesfowler** [comment]
@mfixstsci No, the fix was the added `try/except` statement. I didn't add any default parameters.

**Comment by mfixstsci** [comment]
@julesfowler sorry, the default was there, you just added the message. I see the `try/except` block and it looks okay to me but I do have one more question. Will the page reload with the other data for a specific object and just leave the observation duration field blank?

**Comment by julesfowler** [comment]
@mfixstsci Do you mean, will the auto-population from ExoMAST work?

**Comment by mfixstsci** [comment]
I meant from the url

`https://tlexoctk1.stsci.edu/groups_integrations?k_mag=8.131&transit_duration=0.09089&target=WASP-18+b`

should populate the fields from the url and calculate your observation duration. But lets say that the observation duration is None

`https://tlexoctk1.stsci.edu/groups_integrations?k_mag=8.131&target=WASP-18+b`

Do the target name and kmag fields get populated?

**Comment by julesfowler** [comment]
@mfixstsci Both of the links you provided populate the form on a little locally hosted site. Once these tests pass I'm going to push to `tlexo` and we can finish our testing and see if for any weird reason things are different when they are on the server.

**Pull request merged**
