### PR TITLE
Notebook journey

### PR DESCRIPTION
**Pull request by julesfowler**
I've done 2 things here and I now realize I've one left.

This has : 
1. Renamed the integrations and groups calculator to the groups and integrations calculator. Web edits will be required to match. 
2. Added batch examples to the notebook.

I still need to : 
3. Flesh out the docs and write a little README.

### CODE REVIEW

**Comment by julesfowler** [comment]
@catherine-martlin I realize I'm not super sure exactly what you had in mind as far as adding to the docs. Did you want me to write a little summary in `docs/source/ExoCTK.integrations_groups.rst`? 

Also -- I'll go ahead and rename these to the new convention while I'm monkeying around in here.

**Comment by catherine-martlin** [comment]
@julesfowler - I think it'd be better if you update the README actually. Our plan is to have that description be the main up to date one and then I'll be in charge of distributing the information to the other places we'll be hosting information for users. It's easier to make sure everything matches if we have the one place everyone updates and then a person in charge of dispersing that information to elsewhere. 

Also, you shouldn't actually need to update `docs/source/ExoCTK.integrations_groups.rst` itself. We want those to compile by themselves because they will be recreated every time by the sphinx process thingie when it's run (I don't yet have that terminology hahah). Every time it's run it will build the `.rst` files from your doc strings in your codes.

**Comment by hover2pi** [comment]
Is this still WIP or ready for review @julesfowler ?

**Comment by julesfowler** [comment]
Yup! I think this is ready. Let me get rid of the WIP.

**Pull request merged**
