### PR TITLE
updated scipy req to 1.3 and fixed gtvt dep link

### PR DESCRIPTION
**Pull request by jaymedina**

### CODE REVIEW

**Comment by jaymedina** [comment]
@bourque @catherine-martlin build broke w/ new message on atmospheric retrievals I believe

**Comment by bourque** [comment]
Ah yes, I recognize this error with `TkAgg` from my work in the `implement-aws` branch.  It is because `jwst_gtvt` released a new version of their code that forces the use of the `TkAgg` backend (https://github.com/spacetelescope/jwst_gtvt/commit/b04d547023c157dfed9fa4b4bc6b024305a464cc).

I got around this problem by putting the following in my build:

```bash
git clone https://github.com/spacetelescope/jwst_gtvt.git
cd jwst_gtvt
git checkout cd6bc76f66f478eafbcc71834d3e735c73e03ed5
python setup.py develop
```

It forces a checkout of the version of the code right before that `TkAgg` change was implemented, and installs that version.  Perhaps we can modify our travis build to do the same?

**Comment by jaymedina** [comment]
@bourque thanks so much

**Comment by jaymedina** [comment]
@bourque I think we will need the most recent version of GTVT because they are making enhancements (e.g. PYSIAF dependency) that we will need eventually, so manually pointing to that commit will put off the inevitable. How do we incorporate the `TkAgg` in our environment?

**Pull request merged**
