### PR TITLE
Support python 3.8 and 3.9

### LINKED ISSUE #464: Add support and environment files for Python v3.8 and v3.9
Currently only Python v3.6 and v3.7 are supported. Add `yaml` files to `env` directory and new tests to Travis.

### PR DESCRIPTION
**Pull request by bourque**
This PR adds support for Python 3.8 and 3.9.

Addresses #465 and closes #464

### CODE REVIEW

**Comment by bourque** [comment]
@hover2pi @nespinoza This is ready to go, could one of you review?

**Comment by hover2pi** [comment]
Yup I’ll review it!

**Review by hover2pi — APPROVED** [review]
Works fine on my end. Does this mean `contam_visibility` doesn't work in 3.9 though?

**Comment by bourque** [comment]
@hover2pi Thanks for the review!

RE: `contam_visibility` -- that could very well be true.  There is a larger issue there though, which is that we are using a very specific commit of `jwst_gtvt` for reasons that I can no longer remember.  This is likely not sustainable in the long term (as we are seeing with the 3.9 environment).  We should try to work with @mfixstsci et al. to see if we can make the latest version of `jwst_gtvt` work with ExoCTK, which we can do in a separate issue/PR.

**Pull request merged**
