### PR TITLE
[contam visibility] : add failing test for issue #436

### PR DESCRIPTION
**Pull request by falkben**
adds a failing test for #436

### CODE REVIEW

**Comment by jaymedina** [comment]
Thanks @falkben , I'll review this and get it merged when I come back from vacation (after Nov 6) - can you check to see why the Travis CI build failed?

**Comment by falkben** [comment]
> Thanks @falkben , I'll review this and get it merged when I come back from vacation (after Nov 6) - can you check to see why the Travis CI build failed?

It fails because your fix wasn't in yet :)  I can change the target to your branch if you like?

**Comment by jaymedina** [comment]
> > Thanks @falkben , I'll review this and get it merged when I come back from vacation (after Nov 6) - can you check to see why the Travis CI build failed?
> 
> It fails because your fix wasn't in yet :) I can change the target to your branch if you like?

Hi @falkben ! Looks like PR https://github.com/ExoCTK/exoctk/pull/438#event-3973466419 is now merged. Can you merge the new master to this branch and make a quick commit so Travis can run again?

**Review by jaymedina — APPROVED** [review]
Looks good, thanks for this @falkben !

**Pull request merged**
