### PR TITLE
Make readthedocs work

### PR DESCRIPTION
**Pull request by catherine-martlin**
This is successfully allowing Read the Docs to build!

### CODE REVIEW

**Comment by catherine-martlin** [comment]
Was able to get read the docs to build successfully! 
Still need to complete further updates as the documents aren't building automatically yet, so the pages aren't filled out appropriately.

**Comment by hover2pi** [comment]
Hmmm, I'm trying to figure out why the Python 3.7 build is failing but 3.5 and 3.6 pass. Weird!

**Comment by julesfowler** [comment]
@hover2pi Is there still some issue with 3.7 and `astroconda` compatibility?

**Comment by hover2pi** [comment]
@catherine-martlin We decided to ignore the python 3.7 issue, right? Could you remove the 3.7 test environment from the `.travis.yml` file and push again so the Travis tests get triggered? Once we get all green check marks, I'll merge it and we can figure out the issue with 3.7 later. What do you think?

**Comment by hover2pi** [comment]
Oh boy! I just saw the previous commit. THIS is embarrassing.

**Comment by hover2pi** [comment]
@catherine-martlin In that Travis build, it looks like it is still trying to make a 3.7 egg for some reason.

screen shot 2019-02-08 at 10 57 54 am

I'm not too sure why. Are we caching something or missing something from our `.gitignore`?

**Comment by catherine-martlin** [comment]
I'm pretty confused by this too @hover2pi tbh - it looks like when it's trying to install the exoctk version 0.2.2 it's trying to do so with python 3.7 but I don't know why. Or, I don't know where that is specifically set up. @bourque - would you know anything about that? I was able to remove testing python 3.7 as an environment, but is there something I need to change about our exoctk package itself to make sure it's not trying python 3.7?

**Comment by bourque** [comment]
@catherine-martlin @hover2pi The only thing that stands out to me is that the particular version of `miniconda` being stalled is indicating that it is using Python 3.7 (see https://travis-ci.org/ExoCTK/exoctk/jobs/486619404#L530).  Our environment grabs `http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh`, which is the latest version of `conda` (https://github.com/ExoCTK/exoctk/blob/master/ci/install_conda.sh#L11).  Perhaps we should be grabbing a particular version of `conda` depending on the `$PYTHON_VERSION`

**Comment by catherine-martlin** [comment]
Ohh, okay, I can try making that change on this branch and seeing how it goes. Then we may want to talk about setting that up so we don't run into that issue in the future?

**Comment by bourque** [comment]
@catherine-martlin Before we make any changes like that, I would suggest rebasing this branch to pull in changes I've recently made to the Travis builds (#188), the problem might fix itself?

**Comment by catherine-martlin** [comment]
Rebase here we comeeee.

**Comment by catherine-martlin** [comment]
@bourque @hover2pi - I rebased and double checked that the changes took and they did, but am still getting the error. I was comparing this Travis run with the most recent ones for PR #191 which is passing. It's install step 3 that is crashing here `python setup.py install`. They have the same install of python until after the install of astropy. My branch tries to install `Searching for numpy==1.13.0` which is crashing while the passing PR is not trying numpy until much later and does so with this version: `Searching for numpy==1.15.4`. 
I'm going to try to suss out this possibility.

**Comment by catherine-martlin** [comment]
@hover2pi !!! It passed and I just checked with Read the Docs and this version passed the build there too! This should be good to merge once it's reviewed.

**Comment by hover2pi** [comment]
Awesome! I see the successful build. It still isn't doing the automodule stuff but everything else is there. Nice work!

**Pull request merged**
