### PR TITLE
Upgrade to astropy 4.x

### LINKED ISSUE #440: Upgrade astropy to >=4.0
Currently we are supporting `astropy` `3.2.2`.  We should be able to upgrade to `>=4.0` if we address this deprecation warning:

```
AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
```

### PR DESCRIPTION
**Pull request by bourque**
Closes #440

### CODE REVIEW

**Comment by bourque** [comment]
This should be merged after #441 is merged

**Review by hover2pi — COMMENTED** [review]
This looks fine but why did we downgrade to astropy v3.2.2 in #441 but then upgrade back to v4.0.2 here?

**Comment by bourque** [comment]
@hover2pi I can't remember now even though this was only 5 days ago 😅.  But I will update this branch now that #441 is merged and make sure everything works.

**Comment by bourque** [comment]
@hover2pi @nespinoza Ok, I think this is good to go now.  I've tested locally and I don't see any issues.

**Review by hover2pi — APPROVED** [review]
Sweet.

**Pull request merged**
