### PR TITLE
JWST expansion (visibility only)

### PR DESCRIPTION
**Pull request by jaymedina**
expanding visibility calculator to all JWST instruments

### CODE REVIEW

**Comment by hover2pi** [comment]
@jaymedina Can you put the tabbed visibility plot with all the instruments in this PR and I'll review it all at once? If it's a pain, a new PR is fine. Thanks!

**Comment by jaymedina** [comment]
@hover2pi yes, I can do it in this PR

**Comment by jaymedina** [comment]
@hover2pi one thing to note is that I'm using a modified version of `gtvt` to pull the table that's created (see my PR on their repository https://github.com/spacetelescope/jwst_gtvt/pull/18).

I'm thinking I should wait for that PR to get accepted before we do anything here?

**Comment by jaymedina** [comment]
@hover2pi Just wrapped some things up - I think this is ready for review now. 
Modifications:
- [ ] Visibility is now calculated with GTVT
- [ ] Added GTVT as a dependency
- [ ] Disabled `Contam & Visibility` button until I expand it to NIRCam
- [ ] Modified the text a bit
- [ ] Users can now download the visibility results as a `.txt` file

**Pull request merged**
