### PR TITLE
Added throughputs from pandeia and helpers function to fetch them

### PR DESCRIPTION
**Pull request by hover2pi**
This adds the JWST filters and dispersers to the repo via a function called `helpers.fetch_pandeia_throughputs`. It also adds a convenience function that grabs the curves from the files for the LDC.

### CODE REVIEW

**Comment by hover2pi** [comment]
Ok! This is good to go! The `setup,py` file was pinning the `pyyaml` version incorrectly. Thanks!

**Comment by hover2pi** [comment]
@nespinoza Ok, I verified that all the filters show up in the LDC web page so this is ready to be merged. The drop down list is big but it isn't unmanageable.

**Comment by hover2pi** [comment]
@nespinoza The patch for the Web app running v1.1.0 was to update `svo_filters` to v0.3.1 (#480 ) and the same patch is made in this PR for v1.1.1 by bumping to `svo_filters` v 0.4.1. This is ok to review and merge into `develop` now!

**Comment by hover2pi** [comment]
@nespinoza Resolved conflicts with updated `develop` branch. Ready to merge!

**Comment by nespinoza** [comment]
Hey @hover2pi --- very sorry for the late reply; just testing this on a local branch, freshly installed setup with the python3.7 environment `yaml` file. Bad news is that I haven't managed to download all the exoctk data with this particular branch. I wonder if this is because the data download scripts in this branch are outdated? I'll try again tomorrow, but spent about an hour on this today and no dice.

**Comment by nespinoza** [comment]
Hi @hover2pi,

 All right, finally had the chance to give this a test. It all works like a charm. One quick question: I don't see NIRSpec in the list of instruments. I presume that's really an `svo_filters` thing really, right? Can that be fixed?

 Other than that, this is great. We will need to update JDox, because I just checked and we say the JWST filters are not there --- and now they are :-). Should be an easy change though.

 I'll wait for your answer before closing!

N.

**Comment by hover2pi** [comment]
Hmmm, not sure why NIRSpec is missing. This is actually not a `svo_filters` issue since we generate only the JWST throughputs via `pandeia`. I propose merging this and making a new PR for the NIRSpec throughputs.

**Comment by nespinoza** [comment]
Hey @hover2pi --- OK! Please open a new issue to get this fixed ASAP as a version 1.2.1 bug-fix.

Approving and merging to `develop`!

**Review by nespinoza — APPROVED** [review]

**Pull request merged**
