### PR TITLE
Read the Docs: Updating Phase Constraint

### PR DESCRIPTION
**Pull request by catherine-martlin**
This is to get read the docs working again and to provide the most up to date example of the phase constraint documentation as an example for team members as we push documentation forward

### CODE REVIEW

**Comment by catherine-martlin** [comment]
This branch on RtD is now building successfully - it can be viewed here: https://exoctk.readthedocs.io/en/rtd_phase_constraint/

**Comment by catherine-martlin** [comment]
@nespinoza - This is ready now! You can review the RtDs version here: https://exoctk.readthedocs.io/en/rtd_phase_constraint/tutorials/exoctk.PhaseConstraintCalculator.html#id1

**Comment by catherine-martlin** [comment]
@nespinoza - Hey Nestor! Just a reminder that this is ready for review!

**Comment by nespinoza** [comment]
Oops, sorry for not coming back to this. I already did give it a read and all looks nice! Thanks for this. Approving this then!

**Pull request merged**
