### PR TITLE
Added GET url parameters to web app and backend

### PR DESCRIPTION
**Pull request by mfixstsci**
This is the initial commit. I am able to take a dummy url and then parse the data that is passed into the url query into the form. These are first step for integrating the ExoMAST to ExoCTK data communication.

### CODE REVIEW

**Comment by mfixstsci** [comment]
There is a conflict (looks like white space)? I'll let the reviewer resolve the conflict and merge. The UI now has a little link at the end of the form for the LDC calculator that will link the user to the ExoMAST page for the target they entered.

**Comment by hover2pi** [comment]
@mfixstsci I might hold off on this for a second. I refactored the LDC code and the structure changed a bit. Do you have any objections to me just incorporating these changes into my PR #219 .

**Comment by mfixstsci** [comment]
Not at all @hover2pi! There are some conflict in this PR anyways so go ahead and do whats necessary 👍

**Comment by mfixstsci** [comment]
Added URL retrieval to Groups and Integrations + Contamination Overlap tool. These are the two tools we will be linking from the EXOMAST EXOCTK panel.

**Comment by julesfowler** [comment]
@mfixstsci Is this ready for review -- should this be going into the next release?

**Comment by mfixstsci** [comment]
Maybe hold off on this one @julesfowler, I think this work was done prior to the form validation work. I can look into this further on Friday.

**Comment by julesfowler** [comment]
@mfixstsci We need a frozen completed version by Wednesday. 
Can this wait until the next version?

**Comment by julesfowler** [comment]
@mfixstsci Sooo, can we close this PR?

**Comment by mfixstsci** [comment]
@julesfowler hmmmmmmmmmmmmm yes!

**Pull request closed without merging**
