### PR TITLE
Adding Util Tests

### PR DESCRIPTION
**Pull request by mfixstsci**
This is in reference to #504

### CODE REVIEW

**Comment by mfixstsci** [comment]
@bourque thanks for removing that parameters from the test that was breaking everything. In a perfect world, this operator should be supported and I remember testing it on the web app but it's been a while since I've looked at this. Also, thanks for taking care of the `flake8` `pep` issues 😓

**Comment by bourque** [comment]
@mfixstsci No worries!  Thanks for adding these tests, they look great! 🙌 .  This is ready to merge pending a successful Actions build

**Comment by mfixstsci** [comment]
> @mfixstsci No worries! Thanks for adding these tests, they look great! 🙌 . This is ready to merge pending a successful Actions build

🤞 🤞 🤞 🤞 🤞 🤞 🤞

**Review by bourque — APPROVED** [review]

**Comment by mfixstsci** [comment]
@bourque looks like the `test_medfilt` could still use some work but I started on it and maybe someone can wrap it up later.

**Comment by bourque** [comment]
Send it

**Pull request merged**
