### PR TITLE
Adding the data function back in.

### PR DESCRIPTION
**Pull request by julesfowler**
@hover2pi @kevin218 @mfixstsci @JeffValenti @bourque @jaymedina @catherine-martlin 

This is to throw the data download function back in. 
I'm not sure the button will work every time but it will do something. (And sometimes it works...)

Can anyone take a look and we have can something live?

### CODE REVIEW

**Comment by mfixstsci** [comment]
@julesfowler Thanks for the source code! I was hoping you could elaborate some more on you findings with the download functionality. What's the main issue when a user tries to download the files?

**Comment by mfixstsci** [comment]
Python has a library `mimetypes` that has a class `guess_type` and according to that the mime type is `application/zip`.

```
import mimetypes
mimetypes.guess_type('/path/to/data.zip')
```

Not to terribly interesting, but maybe worth a shot?

**Comment by mfixstsci** [comment]
I went ahead and added the changes but some testing still needs to be performed.

**Comment by julesfowler** [comment]
@mfixstsci Can you look at this soon? Otherwise I can take a peak this weekend.

**Comment by julesfowler** [comment]
Okay -- this is tested (given with a small scale package since the real one wouldn't fit on `tlexo`) and the download completed. I'm merging this in if the tests pass.

**Pull request merged**
