### PR TITLE
Configure @pep8speaks

### LINKED ISSUE #359: Implement @pep8speaks
@pep8speaks allows for a quick and easy check against PEP8 standards in GitHub pull requests.  We should add it to this repository.

### PR DESCRIPTION
**Pull request by bourque**
Closes #359

### CODE REVIEW

**Comment by bourque** [comment]
@nespinoza Could you review?  Unfortunately I don't think we will be able to see @pep8speaks in action until this PR is merged (and a new exoctk PR is opened).

**Comment by nespinoza** [comment]
Hey @bourque --- is Travis failing on this normal?

**Comment by bourque** [comment]
Looks like 2 of the 6 builds got stuck and timed out.  I just spawned a new build, hopefully it works!

**Comment by bourque** [comment]
These builds keep getting stuck, and it's not clear to me why 🤷‍♂ .  I'll try again on Monday.

**Comment by nespinoza** [comment]
All right, no worries! Let me know when you figure this out :-).

**Comment by bourque** [comment]
For some reason Travis has stopped working.  I will investigate.

**Comment by bourque** [comment]
After logging into the Travis account, it does appear that PRs are triggering Travis builds, for example, this PR: https://travis-ci.org/github/ExoCTK/exoctk/builds/670187171

I'm not sure why this information is not getting back to GitHub though.

**Comment by bourque** [comment]
I pushed the "restart build" button on Travis and now GitHub appears to recognize that a Travis build is happening.

**Comment by bourque** [comment]
@nespinoza I finally got the Travis build to run and pass successfully on this, so it should be ready to go!

**Pull request merged**
