### PR TITLE
Patch for v1.1.0 [merge into master]

### PR DESCRIPTION
**Pull request by hover2pi**
v1.1.0 has the same bandpass file for WFC3_IR.G141 and WFC3_IR.G102 grisms. This patch bumps the dependency `svo_filters` to v0.3.1, which has the correct WFC3_IR.G102 grism file.

### CODE REVIEW

**Comment by hover2pi** [comment]
@bourque @nespinoza Is this the correct workflow? I branched from v1.1.0, made the changes and issued the PR to be merged into the v1.1.0 branch? I'm not sure what to merge this into in order to make the v1.1.1 release.

**Comment by hover2pi** [comment]
@bourque @nespinoza Ok, I think this is ready. As soon as it's merged, we can deploy it to `tlexo`.

**Comment by bourque** [comment]
This diagram shows the proper workflow we should take here, I think:

git_workflow

Note that the release branch should be merged into *both* `master` and `develop`.  So I think we are fine to merge in this PR as it is, and we will have to open another PR that merges `v1.1.1` into `develop`.

Once this PR is merged into `master`, we can create a GitHub `release`/`tag` off of `master`, which will officially mark the release of the new version.

**Comment by bourque** [comment]
I created the PR to merge into `develop` here: #482

**Comment by hover2pi** [comment]
@bourque Can you also review it so I can merge? It's just some dependency changes. I was able to make the fix with a new release of `svo_filters`.

**Review by bourque — APPROVED** [review]

**Comment by bourque** [comment]
@hover2pi Ah yes, sorry about that.  I forgot to hit the approval buttons yesterday.  The changes look good to me, but I would suggest we test on the test server before we merge.

**Comment by bourque** [comment]
@hover2pi This is now redundant with #484 and can be closed, correct?

**Comment by bourque** [comment]
@hover2pi This is now redundant with #484 and can be closed, correct?

**Pull request closed without merging**
