### PR TITLE
Modelgrid fixes

### PR DESCRIPTION
**Pull request by hover2pi**
Added a complete minimal model grid and removed the effective radius calculation from the interpolator.

### CODE REVIEW

**Comment by hover2pi** [comment]
`pytest` is not running! Must add this to `.travis.yml`.

**Comment by hover2pi** [comment]
Ok, this is good to go. `pytest` is running too (#140 ).

**Comment by hover2pi** [comment]
The precomputed model grid pickle retained the path from my local machine so it was failing when the Travis loaded it. I just removed the precomputed files and will let Travis generate them.

What I should probably do is have these files generated as part of the install procedure, though it's not vital. This just makes the first model grid call take an extra 30 seconds.

**Comment by hover2pi** [comment]
BOOOOOOO! The linux tests are passing but the OSX tests are still looking for tests in an `ExoCTK` (not `exoctk`) directory. I don't get it.

**Comment by hover2pi** [comment]
Ok I think I fixed it!

**Comment by julesfowler** [comment]
The changes look pretty reasonable and straightforward. I'll approve it -- and leave it for you to merge at your leisure/when the time is right.

**Pull request merged**
