### PR TITLE
Adding Github Actions

### PR DESCRIPTION
**Pull request by mfixstsci**

### CODE REVIEW

**Comment by bourque** [comment]
@mfixstsci Is this still a WIP?  It seems like it might be finished so I just wanted to check.

**Comment by mfixstsci** [comment]
@bourque I went ahead and rebased the branch and removed the conflicts. This should be ready to go pending review!

**Comment by mfixstsci** [comment]
Just to close the loop, the build is passing: 
https://github.com/mfixstsci/exoctk/actions/runs/748558861

**Comment by hover2pi** [comment]
@mfixstsci Is this ready for review or still WIP?

**Comment by mfixstsci** [comment]
@hover2pi it's ready for review if you wanna do it!

**Review by bourque — APPROVED** [review]
This looks good to me @mfixstsci!

**Comment by mfixstsci** [comment]
@hover2pi if it looks good to you, send it.

**Pull request merged**
