### PR TITLE
Fix pip & asteval env issues

### LINKED ISSUE #455: environment-xx.yml issues with Pip and Asteval
(base) zor:env dlong$ conda env create -f environment-3.7.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

I added "- pip=20.2.4" to environment-3.7.yml

"setup.py install" fails with an error:

error: asteval 0.9.13 is installed but asteval>=0.9.16 is required by {'lmfit'}
(although I see there is an open issue to remove lmfit)

Fixed by changing "- asteval==0.9.13" to "- asteval==0.9.16"

Some warnings, but no more errors.

I checked for the same problems in environment-3.6.yml:

(base) zor:env dlong$ conda env create -f environment-3.6.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

Made same changes for pip and asteval as in environment-3.7.yml.

### PR DESCRIPTION
**Pull request by bourque**
I re-created the 3.6 and 3.7 environment from scratch with these changes and everything installed without errors!

Closes #455

### CODE REVIEW

**Comment by bourque** [comment]
@hover2pi Could you also review this one? Pls thx? 😅

**Review by hover2pi — APPROVED** [review]
All I see is the `pip` dependency. Was that all?

**Comment by hover2pi** [comment]
And there is a `sphinx` install issue in Travis now. Does it just need to be added to the environment files?

**Comment by bourque** [comment]
@hover2pi I fixed the Travis builds on this, so I will merge it now!  Thanks again for the review.

**Pull request merged**
