### PR TITLE
Adding simulations script for __init__.py

### PR DESCRIPTION
**Pull request by mfixstsci**
adding `simulations` to `__init__.py` for importability.

### CODE REVIEW

**Comment by mfixstsci** [comment]
Looks like the travis build is failing because the of `sphinx` have you seen this before in previous PRs @catherine-martlin or @julesfowler?

**Comment by catherine-martlin** [comment]
I think this issue might be resolved in PR #318 - we should think about merging that fix in.

**Comment by catherine-martlin** [comment]
Well, more than just think about it.

**Comment by mfixstsci** [comment]
@catherine-martlin, should be good to go. Let me know if the rebasing was successful.

**Pull request merged**
