### PR TITLE
Re-add exoctk-3.7 environment and corresponding travis build

### LINKED ISSUE #243: Re-support Python 3.7 in Travis builds
Recently we removed the Travis build for the `exoctk-3.7` environment.  We should try adding that back, and if it is still causing issues we should try to understand why.

### PR DESCRIPTION
**Pull request by bourque**
This PR adds a Travis CI build for the python 3.7/`exoctk-3.7` environment.

Closes #243

### CODE REVIEW

**Comment by bourque** [comment]
@julesfowler and/or @hover2pi, this looks ready to jetty, could you review?

**Comment by bourque** [comment]
@julesfowler pls review

**Comment by bourque** [comment]
I need to re-visit the `bandpass.apply` function as figure out why exactly I am seeing different behavior depending on python and/or `svo_filter` versions in regards to how many values are returned.

**Comment by bourque** [comment]
Ok so I have determined that in a `3.6` environment, `bandpass.apply()` returns a `tuple` of length 2, whereas in a `3.7` environment, it returns an `numpy.ndarray `.  For the testing functions, these have dimensions of `(17,100)`, `(17,58)`, `(10,17,4)`, and `(17,100)`.  

In the situation where a `tuple` is returned, the first element appears to be the same `numpy.ndarray` as to what is returned in the `3.7` environment, that is, the values have dimensions of `(17,100)`, `(17,58)`, `(10,17,4)`, and `(17,100)`.  Also by a quick glance by eye, the values of the arrays appear to be the same.  The second element in the tuple appears to be arrays of the same dimensions, only with all `nan` values in them.  

Therefore, I believe the proposed code changes in this PR will not affect the resulting data, since in both environments, either only one value is returned (the correct value), or only the first value in the returned tuple (also the correct value) is used.

As for why the python version matters on what is returned by `bandpass.apply` -- `bandpass` is a parameter passed to `LDC.calculate`, the value of which is derived from `svo_filters.Filter()`, so something is going on within the `svo_filters` library to cause this.  I could go digging deeper, but seeing that `svo_filters` is an external dependency that we don't really have control over, I figure that we will just have to deal with this behavior anyways.

@julesfowler Do you agree?

**Comment by bourque** [comment]
@julesfowler If you agree with my above comments, I think this is ready to go!

**Comment by julesfowler** [comment]
@bourque I feel comfy with your testing -- thanks for thoroughly investigating.

**Pull request merged**
