### PR TITLE
1.0 Release

### PR DESCRIPTION
**Pull request by bourque**
Merging this PR will update the `exoctk` version number and officially signify our 1.0 release!

### CODE REVIEW

**Comment by julesfowler** [comment]
I want to make a list of everything we need to do before this can go down : 

- [x] Change util from 0.4.0 --> 1.0.
- [ ] Documentation updates / PR finalized : https://github.com/ExoCTK/exoctk/pull/325
- [ ] `tlexo` operating as expected
- [ ] limb darkening calculator smoothed out
- [ ] phase constraint PR approved / merged / etc

**Comment by mfixstsci** [comment]
@bourque and @julesfowler the limb darkening PR was merged. Can we tick that box off?

**Comment by bourque** [comment]
@mfixstsci Turns out there was another problem with it when testing on the test server (see Slack message):

```
Traceback (most recent call last):
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/exoctk_app/app_exoctk.py", line 178, in limb_darkening
    ld.calculate(*star_params, prof, mu_min=float(form.mu_min.data), bandpass=bandpass)
  File "/internal/data1/exodeploy/exoctk/exoctk/limb_darkening/limb_darkening_fit.py", line 264, in calculate
    mg_min = self.model_grid.wave_rng[0].value
AttributeError: 'int' object has no attribute 'value'
```

Do you know what is going on here?

**Comment by julesfowler** [comment]
@mfixstsci Any ideas? Do you have a timeline for when you can look at this?

**Comment by mfixstsci** [comment]
@julesfowler I made the change and it was passing just fine on `tlexo`. Do we have any versioning issues with `astropy.units`? I am back today and will get on this first thing.

**Comment by bourque** [comment]
I can confirm that ReadTheDocs builds are passing on the latest `master` branch.  Everything looks fine when viewing the docs, and all links are working and point to where is expected.

**Comment by bourque** [comment]
In regards to the LDC issue -- I figured out that we can get the LDC web tool and the LDC tests to pass if this block of code in `limb_darkening_fit.py` is commented out:

```python
        # # Make sure the bandpass has coverage
        # bp_min = bandpass.wave_min.value
        # bp_max = bandpass.wave_max.value
        # mg_min = self.model_grid.wave_rng[0]
        # mg_max = self.model_grid.wave_rng[-1]
        # if bp_min < mg_min or bp_max > mg_max:
        #     raise ValueError('Bandpass {} not covered by model grid of\
        #                       wavelength range {}'.format(bandpass.filterID,
        #                                                   self.model_grid
        #                                                       .wave_rng))
```

@julesfowler @hover2pi Do any of you know if this check is essential?

**Comment by julesfowler** [comment]
@bourque At this point, I say we push it to `tlexo` and try to test it.

**Comment by bourque** [comment]
With #332 merged, I think it is safe to say the LDC is good to go now.

**Comment by bourque** [comment]
All we are waiting on is to make sure that everything on `tlexo` is fine!

**Pull request merged**
